import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "@components/Layout";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "react-query";
import { Provider } from "react-redux";
import { store } from "redux/store";

function MyApp({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  return (
    <>
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
          <Head>
            <title>Movie Geeks</title>
            <meta name="Movie Geeks" content="Generated by create next app" />
            <link rel="icon" href="/movie-icon.png" />
          </Head>
          <Layout>
            <Toaster />
            <main>
              <Component {...pageProps} />
            </main>
          </Layout>
        </QueryClientProvider>
      </Provider>
    </>
  );
}

export default MyApp;
